/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-southeast-2',
  aws_cognito_identity_pool_id: '',
  aws_cognito_region: 'ap-southeast-2',
  aws_user_pools_id: '',
  aws_user_pools_web_client_id: '',
  oauth: {},
  aws_appsync_graphqlEndpoint: '',
  aws_appsync_region: 'ap-southeast-2',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_appsync_apiKey: '',
  aws_cloud_logic_custom: [],
  aws_mobile_analytics_app_id: '',
  aws_mobile_analytics_app_region: 'us-west-2',
  aws_user_files_s3_bucket: '',
  aws_user_files_s3_bucket_region: 'ap-southeast-2',
  aws_dynamodb_all_tables_region: 'ap-southeast-2',
  aws_dynamodb_table_schemas: [
    {
      tableName: '',
      region: 'ap-southeast-2',
    },
  ],
};

export default awsmobile;
