import {StyleSheet, Dimensions} from 'react-native';
import {Colors} from 'react-native/Libraries/NewAppScreen';
import {moderateScale} from 'utilities/scaling';
const {height, width} = Dimensions.get('screen');
export const palette = {
  purpleLight: '#8C6FF7',
  purplePrimary: '#5A31F4',
  purpleDark: '#3F22AB',

  lightestGreen: '#EBFFE8',
  lightGreen: '#C1E1BC',
  mediumGreen: '#31442E',

  lightestSand: '#FFF',
  black: '#0B0B0B',
  white: '#F0F2F3',

  darkSunset: '#A46750',
  sunset: '#EC9472',
  vibrantSunset: '#F78255',
  lightSunset: '#FFC7B1',

  darkSand: '#B7AC9B',
  sand: '#E2D6C4',
  lightSand: '#FFF9EF',

  grass: '#10270B',
  muted: '#BBBBB4',
  lightGrey: '#DCDCDC',
};

const fontSizing = {
  bigNumber: 32,
  heading: 26,
  subheading: 21,
  body: 16,
  subtitle: 12,
  caption: 12,
};

export const colors = {
  lightSand: palette.lightSand,
  sand: palette.sand,
  darkSand: palette.darkSand,
  lightSunset: palette.lightSunset,
  darkSunset: palette.darkSunset,
  sunset: palette.sunset,
  vibrantSunset: palette.vibrantSunset,
  lightestGreen: palette.lightestGreen,
  lightGreen: palette.lightGreen,
  mediumGreen: palette.grass,
  green: palette.grass,
  mainBackground: palette.sand,
  cardPrimaryBackground: palette.purplePrimary,
  muted: palette.muted,
  switch_off: palette.muted,
  switch_on: palette.sunset,
  lightgrey: palette.lightGrey,
};

export const spacing = {
  default: 15,
  small: 5,
  medium: 10,
  large: 20,
  xl: 25,
};

export default StyleSheet.create({
  backgroundColor: {
    color: colors.muted,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  maincontainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.sand,
  },
  textInput: {
    height: 62,
    margin: 10,
    paddingHorizontal: spacing.large,
    width: '80%',
    color: 'black',
    backgroundColor: 'white',
    borderColor: 'gray',
    borderBottomWidth: 1,
    fontSize: 21,
    textTransform: 'uppercase',
    fontFamily: 'roboto',
    fontWeight: 'bold',
  },
  textInputError: {
    height: 62,
    margin: 10,
    paddingHorizontal: spacing.large,
    width: '80%',
    color: 'red',
    backgroundColor: 'white',
    borderColor: 'gray',
    borderBottomWidth: 1,
    fontSize: 21,
    textTransform: 'uppercase',
    fontFamily: 'roboto',
    fontWeight: 'bold',
    borderWidth: 1,
    borderColor: 'red',
  },

  listcontainer: {
    flex: 1,
    width: '100%',
  },
  newsfeedNames: {
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  newsfeedIcons: {
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 10,
  },
  newsfeedComments: {
    flex: 1,
    maxHeight: 100,
    backgroundColor: 'white',
    marginBottom: 20,
  },
  newsfeedCard: {
    height: 300,
    backgroundColor: 'white',
    marginBottom: 0,
  },
  newsfeedListItem: {
    padding: 10,
    fontSize: 18,
  },
  newsfeedHorizontalListContainer: {
    width: '100%',
    padding: 5,
  },
  newsfeedHorizontalCard: {
    height: 75,
    width: 75,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
    margin: 5,
  },
  newsfeedHorizontalListItem: {
    padding: 10,
    fontSize: 18,
  },
  notificationItem: {
    padding: 10,
    fontSize: 12,
  },
  settingsItem: {
    padding: 10,
    fontSize: 22,
  },
  buttonContainer: {
    backgroundColor: colors.green,
    borderRadius: 5,
    padding: 10,
    margin: 20,
  },
  buttonText: {
    fontSize: 20,
    color: '#fff',
  },
  text: {
    color: '#101010',
    fontSize: 24,
    fontWeight: 'bold',
  },
  headerText: {
    color: '#101010',
    fontSize: 32,
    fontWeight: 'bold',
  },
  card: {
    width: 350,
    height: 100,
    borderRadius: 10,
    backgroundColor: '#101010',
    margin: 10,
    padding: 10,
    alignItems: 'center',
  },
  cardText: {
    fontSize: 18,
    color: '#ffd700',
    marginBottom: 5,
  },
  // Profile Stack
  profileStackHeaderContainer: {
    flexDirection: 'row',
    flex: 1,
    backgroundColor: colors.sand,
  },
  profileContainer: {
    flex: 1,
    padding: 0,
    width: width,
  },
  profileNameHeader: {
    flexDirection: 'row',
    padding: 5,
  },
  profileTextHeading: {
    fontSize: fontSizing.heading,
    marginBottom: 0,
    padding: 0,
  },
  profileTextSubheading: {
    fontSize: fontSizing.subheading,
  },
  //Avatars
  avatarmain: {
    height: 75,
    width: 75,
    margin: 5,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
    backgroundColor: '#aaffff',
  },
  avatarWithName: {
    height: 50,
    width: 50,
    margin: 0,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    backgroundColor: '#aaffff',
  },
  avatarWithNameText: {
    fontSize: fontSizing.subtitle,
    textAlign: 'center',
  },
  //Buttons
  buttonSelected: {
    margin: 10,
    padding: 5,
    borderRadius: 20,
    height: 100,
    width: 100,
    backgroundColor: colors.green,
    alignItems: 'center',
    alignSelf: 'center',
  },
  buttonUnselected: {
    margin: 10,
    padding: 5,
    borderRadius: 20,
    height: 100,
    width: 100,
    backgroundColor: colors.sand,
    alignItems: 'center',
    alignSelf: 'center',
  },
  buttonSelected4: {
    margin: 10,
    padding: 5,
    borderRadius: 10,
    height: 75,
    width: 75,
    backgroundColor: colors.green,
    alignItems: 'center',
    alignSelf: 'center',
  },
  buttonUnselected4: {
    margin: 10,
    padding: 5,
    borderRadius: 10,
    height: 75,
    width: 75,
    backgroundColor: colors.sand,
    alignItems: 'center',
    alignSelf: 'center',
  },
  buttonsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  fullScreenPrimaryButton: {
    borderRadius: 30,
    height: 60,
    width: 300,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginVertical: spacing.default,
    backgroundColor: colors.sunset,
  },
  fullScreenDefaultButton: {
    borderRadius: 30,
    height: 60,
    width: 300,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginVertical: spacing.default,
    backgroundColor: 'white',
  },
  fullScreenSecondaryButton: {
    borderRadius: 30,
    height: 60,
    width: 300,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginVertical: spacing.default,
    backgroundColor: colors.green,
    textTransform: 'capitalize',
  },
  ctaButton: {
    paddingHorizontal: 5,
    minWidth: 60,
    borderRadius: 15,
    justifyContent: 'center',
    alignContent: 'center',
  },
  buttonsBackground: {
    backgroundColor: 'white',
    borderRadius: 15,
    padding: 10,
    borderWidth: 0,
    margin: 2,
  },
  buttonsText: {
    padding: 10,
    fontSize: fontSizing.small,
    textAlign: 'center',
    fontWeight: 'bold',
    fontFamily: 'roboto-boldCondensed',
  },
  primaryButtonText: {
    fontSize: fontSizing.subheading,
    textAlign: 'center',
    color: 'white',
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  defaultButtonText: {
    fontSize: fontSizing.subheading,
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'black',
    textTransform: 'uppercase',
  },
  //Text
  screenTitle: {
    fontSize: 21,
    textAlign: 'center',
    textTransform: 'uppercase',
    fontFamily: 'roboto',
    fontWeight: 'bold',
  },
  pageTitle: {
    fontSize: moderateScale(18),
    marginTop: spacing.medium,
    padding: spacing.medium,
    fontFamily: 'roboto',
  },
  smallText: {
    fontSize: moderateScale(fontSizing.caption),
    //marginTop: spacing.medium,
    paddingHorizontal: spacing.medium,
    fontFamily: 'roboto-boldCondensed',
  },
  optionsText: {
    fontSize: moderateScale(18),
    fontFamily: 'roboto-boldCondensed',
    marginHorizontal: 10,
    textTransform: 'uppercase',
  },
  checkMark: {
    paddingHorizontal: 10,
  },
  smallTextWhite: {
    fontSize: fontSizing.header,
    color: 'white',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  smallTextGreen: {
    fontSize: fontSizing.header,
    color: colors.green,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  largeTextGreen: {
    fontSize: moderateScale(fontSizing.bigNumber),
    color: colors.green,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  largeTextWhite: {
    fontSize: moderateScale(fontSizing.bigNumber),
    color: 'white',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  avatarTextSelected: {
    fontSize: moderateScale(9),
    fontFamily: 'roboto-boldCondensed',
    color: palette.grass,
    padding: 2,
    textAlign: 'center',
    //backgroundColor:'red'
  },
  buttonsText: {
    fontSize: moderateScale(fontSizing.subtitle),
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  buttonsCtaText: {
    fontSize: fontSizing.subheading,
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  buttonPrimary: {
    backgroundColor: palette.sunset,
    borderRadius: 20,
    padding: 5,
    margin: 5,
  },
});
